spring:
  profiles:
    active:
      - dev
      
---

spring:
  profiles: dev
    application:
      name: miroservice-springcloud-config-dev
      
---

spring:
  profiles: test
  application:
    name: miroservice-springcloud-config-test